### ISSUE TITLE
Clarification needed for what this does

### ISSUE THREAD

**Issue by bung69** [rosineygp/proxmox-pci-switcher#23]
can you provide clarification on what this does?

assuming it allows switching a secondary GPU between multiple VM's while running?

Thanks

**Comment by rosineygp** [comment]
Hi,

The main idea is:

you have one GPU, and switch among vms, but only one vm can use the resource, because PCI passthrough can't provide this kind of utilization.

But, if you have 2 GPUs you can configure grupos (eg. GPU1, and GPU2) and switch among the group.

In another words is just a switcher, like a TV you have a lot of channels but just watch one... in our case we have a lot of vms (channels) and just one GPU (tv).
